name: Test Docker Image

on: [pull_request]

jobs:
  test:
    name: Validate image builds

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint the Dockerfile
        uses: brpaz/hadolint-action@v1.5.0

      - name: Build the Docker image
        run: docker build .
